In [3]:
import numpy as np

In [4]:
a = np.array([[1, 6], 
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [6]:
a_centered = np.subtract (a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [7]:
a_centered_sp = np.dot(a_centered, 2)
a_centered_sp

array([[-2. , -4.8],
       [ 0. , -0.8],
       [ 2. ,  5.2],
       [ 2. ,  3.2],
       [-2. , -2.8]])

In [8]:
a_centered_sp % 4

array([[2. , 3.2],
       [0. , 3.2],
       [2. , 1.2],
       [2. , 3.2],
       [2. , 1.2]])